### ISSUE TITLE
Right clicking with a mffs machine onto another mffs machine

### ISSUE THREAD

**Issue by dmodoomsirius** [BuiltBrokenModding/BBM-MFFS#28]
When i right clicked on any mffs machine with another mffs machine it places it down as tho you are right clicking to place another one down.

Need to test seeing if it opens the one I am clicking on rather then the new one.

**Comment by Poopsicle360** [comment]
Will no longer place the block upon clicking with a item in hand.

Fixed https://github.com/BuiltBrokenModding/BBM-MFFS/commit/ffb601a012e6dad03fc908230b8b628af7e97a6b
