### ISSUE TITLE
Right clicking with a lever doesn't open gui of machine

### ISSUE THREAD

**Issue by dmodoomsirius** [BuiltBrokenModding/BBM-MFFS#29]
When I right clicked on all the mffs machines with a lever it didn't open the gui had to switch with an empty hand or a mffs module in order to open the gui. Haven't tested with the rest of the items yet.

**Comment by Poopsicle360** [comment]
Fixed https://github.com/BuiltBrokenModding/BBM-MFFS/commit/ffb601a012e6dad03fc908230b8b628af7e97a6b
