### ISSUE TITLE
Custom Mode crashes game

### ISSUE THREAD

**Issue by pwnage-pineapple** [BuiltBrokenModding/BBM-MFFS#31]
When placing a custom mode into the projector. My game crashed. The log is available on pastebin [here](http://pastebin.com/E7fGjxjc).

**Comment by DarkGuardsman** [comment]
Looks like something sent a null packet. However, the version in the error is not longer supported. We are moving to a different version being developed by a 3rd party. Which will replace the existing version set that was released on curse.
